### ISSUE TITLE
Index határérték kezelés

### ISSUE THREAD

**Issue by Sholwa** [Sholwa/mems-beadando#1]
A beolvasott zene lista index határának kezelése. Jelenleg az előző, következő szám váltásakor tovább lépteti az indexet(számot a program) akkor is ha nincs több szám. Ekkor elszáll a kód természetesen, és ez javítani kell.

**Comment by shoetermarco** [comment]
Esetleg beolvasni a zenéket és egy playlist-hez rendelni őket. Ha annak vége, akkor return playlist. Gyakorlatban kicsit nehezebb...

**Comment by Sholwa** [comment]
>           Esetleg beolvasni a zenéket és egy playlist-hez rendelni őket. Ha annak vége, akkor return playlist. Gyakorlatban kicsit nehezebb...

Jelenleg valami hasonló történik, egy  "l" nevű változóba kerül bele az össze mp3 fájl az adott mappában.  LÁsd:

```
path="c:/rPI_music_box/music"
os.chdir(path) # könyvtár váltás, hogy ne kelljen elérési utat definiálni a zenék lejátszásakor
l = []
if os.path.isdir(path) == True: # zene könyvtár meglétének ellenőrzése
    print("==========================================")
    print("The music folder exists")
    print("==========================================")
    for files in os.listdir(path): # zene könyvtár listázása
        if files.endswith(".mp3"): # mp3 kiterejsztésű fájlokra szűrés
            l.append(files) # lejatászi lista létrehozása
            print(files)


```
Ezt most úgy használja a program hogy előző következő gombokra lépteti az indexet egyel:
```
def next():
    global index
    index += 1
    mp3.load(l[index])
    mp3.play
```


A gond az hogy ha pl 5 szám van az l változóban, akkor 0,1,2,3,4,5 ig van az index. amikor az 5-ös index-ű szám szól és nyomsz egy következő akkor megpróbálja betölteni ezt: `mp3.load(l[6])`
de nincs 6-os index. Ezt kell megoldani itt.

**Comment by Sholwa** [comment]
@shoetermarco  Szia, sikerült vele foglalkozni? Ha elakadtál szólj.

**Comment by Sholwa** [comment]
Sikerült megoldani a problémát a következő részek módosításával:
```
                lSize=len(l) # számok darabszámának tárolása

                elif event.key == ord ( "Ĕ" ):
                    index -= 1
                    if index < 0:
                        index = lSize-1
                    print(index) # RPI-n nem kell
                    previous() # Bal
                elif event.key == ord ( "ē" ):
                    index += 1
                    if index == lSize:
                        index = 0
                    print(index) #RPI-n nem kell
                    next() # Jobb


```

Most commitoltam. kipróbálható.
