### ISSUE TITLE
SenseHat LED matrix

### ISSUE THREAD

**Issue by Sholwa** [Sholwa/mems-beadando#4]
### Szám címének megjelenítése
- [X] éppen lejátszott szám kijelzése. Kommentként szintén beszúrva egy lehetséges megoldás De még finomításra szorul. Jelenleg egyszer jeleníti meg a zeneszámot, de jó volna ha azt ismétlődően tenné amíg a szám szól, vagy amig meg nem állítják.
- [ ] A kommentként beszúrt megoldás működik de sajnos amig véget nem ér a szám kijelzése addig a gombokra nem reagál. Meg kell oldani hogy megszakítsa a kiírást és azonnal számot váltson.

### Joystick gombok megnyomásakor rajzolandó funkció logók
- [x] Play gomb 3szög logó kirajzolás
- [x] Pause   ||   logó kirajzolás
- [x] Next   >   logó kirajzolás
- [x] Previous   <  logó kirajzolás
- [ ] Shuffle x  logó kirajzolás
- [ ] a fenti logók kódba illesztése:
-1-a megjelenítés bekerülhet a megfelelő függvényekhez a szám kijelzés elé, mondjuk 1 másodpercig.
-2-ezután a szám kijelzés addig ismétlődik míg vége nincs a számnak, vagy szám váltás történik.

**Comment by Sholwa** [comment]
A kommentként beszúrt megoldás működik de sajnos amig véget nem ér a szám kijelzése addig a gombokra nem reagál. Meg kell oldani hogy megszakítsa a kiírást és azonnal számot váltson.

**Comment by MasterPepinho** [comment]
a play gomb megjelenítésére ezt bele lehet tenni. Csinálom a többit is. Remélem nem lesz 90 fokkal elfordulva :D 

sense.set_pixel(1, 1, (0, 0, 255))
sense.set_pixel(1, 2, (0, 0, 255))
sense.set_pixel(1, 3, (0, 0, 255))
sense.set_pixel(1, 4, (0, 0, 255))
sense.set_pixel(1, 5, (0, 0, 255))
sense.set_pixel(2, 2, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(3, 3, (0, 0, 255))

**Comment by MasterPepinho** [comment]
itt a stop, azt nem tudom, hogy kitöltött legyen e az ábra vagy ne, de a stoppot kitöltve csináltam

sense.set_pixel(2, 2, (0, 0, 255))
sense.set_pixel(3, 2, (0, 0, 255))
sense.set_pixel(4, 2, (0, 0, 255))
sense.set_pixel(5, 2, (0, 0, 255))
sense.set_pixel(2, 3, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(2, 5, (0, 0, 255))
sense.set_pixel(5, 3, (0, 0, 255))
sense.set_pixel(5, 4, (0, 0, 255))
sense.set_pixel(5, 5, (0, 0, 255))
sense.set_pixel(3, 5, (0, 0, 255))
sense.set_pixel(4, 5, (0, 0, 255))
sense.set_pixel(3, 3, (0, 0, 255))
sense.set_pixel(3, 4, (0, 0, 255))
sense.set_pixel(4, 3, (0, 0, 255))
sense.set_pixel(4, 4, (0, 0, 255))

**Comment by MasterPepinho** [comment]
ez pedig a pause... módosíthatunk rajta mindegyiken

sense.set_pixel(2, 1, (0, 0, 255))
sense.set_pixel(2, 2, (0, 0, 255))
sense.set_pixel(2, 3, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(2, 5, (0, 0, 255))
sense.set_pixel(2, 6, (0, 0, 255))
sense.set_pixel(4, 1, (0, 0, 255))
sense.set_pixel(4, 2, (0, 0, 255))
sense.set_pixel(4, 3, (0, 0, 255))
sense.set_pixel(4, 4, (0, 0, 255))
sense.set_pixel(4, 5, (0, 0, 255))
sense.set_pixel(4, 6, (0, 0, 255))

**Comment by MasterPepinho** [comment]
[sensehat.xlsx](https://github.com/Sholwa/mems-beadando/files/2653369/sensehat.xlsx)

valami ilyesmi ábrákat kellene megvalósítani, nem?

**Comment by Sholwa** [comment]
Király, Délelőtt meg nézem hogy néznek ki, aztán lehet a kodba is beszurom.

**Comment by MasterPepinho** [comment]
Oksa. Szerintem finomítani kellene rajta, legalább olyanra mint az excel amit feltöltöttem. Illetve az emulatorba csinálgattam, ott kellett használni a sense.clear()-t, mert különben egybe rajzolta volna. Élesben nem tudom, hogy fog kinézni, de akkor teszteld le holnap és módosítunk rajta max.

**Comment by MasterPepinho** [comment]
Na ezeket az ábrákat mondanám már tűrhetőnek:

PLAY: 

sense.set_pixel(1, 1, (0, 0, 255))
sense.set_pixel(1, 2, (0, 0, 255))
sense.set_pixel(1, 3, (0, 0, 255))
sense.set_pixel(1, 4, (0, 0, 255))
sense.set_pixel(1, 5, (0, 0, 255))
sense.set_pixel(2, 2, (0, 0, 255))
sense.set_pixel(2, 3, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(3, 3, (0, 0, 255))

STOP:

sense.set_pixel(1, 2, (0, 0, 255))
sense.set_pixel(1, 3, (0, 0, 255))
sense.set_pixel(1, 4, (0, 0, 255))
sense.set_pixel(2, 2, (0, 0, 255))
sense.set_pixel(2, 3, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(3, 2, (0, 0, 255))
sense.set_pixel(3, 3, (0, 0, 255))
sense.set_pixel(3, 4, (0, 0, 255))


VISSZA: 
sense.set_pixel(0, 3, (0, 0, 255))
sense.set_pixel(1, 2, (0, 0, 255))
sense.set_pixel(1, 3, (0, 0, 255))
sense.set_pixel(1, 4, (0, 0, 255))
sense.set_pixel(2, 1, (0, 0, 255))
sense.set_pixel(2, 2, (0, 0, 255))
sense.set_pixel(2, 3, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(2, 5, (0, 0, 255))
sense.set_pixel(4, 4, (0, 0, 255))
sense.set_pixel(5, 3, (0, 0, 255))
sense.set_pixel(5, 4, (0, 0, 255))
sense.set_pixel(5, 5, (0, 0, 255))
sense.set_pixel(6, 2, (0, 0, 255))
sense.set_pixel(6, 3, (0, 0, 255))
sense.set_pixel(6, 4, (0, 0, 255))
sense.set_pixel(6, 5, (0, 0, 255))
sense.set_pixel(6, 6, (0, 0, 255))




PAUSE:

sense.set_pixel(0, 1, (0, 0, 255))
sense.set_pixel(0, 2, (0, 0, 255))
sense.set_pixel(0, 3, (0, 0, 255))
sense.set_pixel(0, 4, (0, 0, 255))
sense.set_pixel(0, 5, (0, 0, 255))

sense.set_pixel(1, 1, (0, 0, 255))
sense.set_pixel(1, 2, (0, 0, 255))
sense.set_pixel(1, 3, (0, 0, 255))
sense.set_pixel(1, 4, (0, 0, 255))
sense.set_pixel(1, 5, (0, 0, 255))

sense.set_pixel(3, 1, (0, 0, 255))
sense.set_pixel(3, 2, (0, 0, 255))
sense.set_pixel(3, 3, (0, 0, 255))
sense.set_pixel(3, 4, (0, 0, 255))
sense.set_pixel(3, 5, (0, 0, 255))

sense.set_pixel(4, 1, (0, 0, 255))
sense.set_pixel(4, 2, (0, 0, 255))
sense.set_pixel(4, 3, (0, 0, 255))
sense.set_pixel(4, 4, (0, 0, 255))
sense.set_pixel(4, 5, (0, 0, 255))

ELŐRE:

sense.set_pixel(1, 2, (0, 0, 255))
sense.set_pixel(1, 3, (0, 0, 255))
sense.set_pixel(1, 4, (0, 0, 255))
sense.set_pixel(1, 5, (0, 0, 255))
sense.set_pixel(1, 6, (0, 0, 255))
sense.set_pixel(2, 3, (0, 0, 255))
sense.set_pixel(2, 4, (0, 0, 255))
sense.set_pixel(2, 5, (0, 0, 255))
sense.set_pixel(3, 4, (0, 0, 255))
sense.set_pixel(5, 1, (0, 0, 255))
sense.set_pixel(5, 2, (0, 0, 255))
sense.set_pixel(5, 3, (0, 0, 255))
sense.set_pixel(5, 4, (0, 0, 255))
sense.set_pixel(5, 5, (0, 0, 255))
sense.set_pixel(6, 2, (0, 0, 255))
sense.set_pixel(6, 3, (0, 0, 255))
sense.set_pixel(6, 4, (0, 0, 255))
sense.set_pixel(7, 3, (0, 0, 255))

**Comment by Sholwa** [comment]
@MasterPepinho  az alábbi kódot beszúrva tudod az emulatorban próbálgatnia a senseHat joystic-ot használva a függvényeket. 
Ugye jelenleg így néz ki a kód, és ezt kéne igazítani hogy megszakadjon a számkiírás ha számot váltunk, megnyomunk valamit. Illetve ebbe beillesztheted még hogy írja aki mondjuk 1 másodpercig a logókat, utána a szám címet. Ahogy beszéltük.

Az emulatorban a joystickot a <kbd>fel</kbd> , <kbd>le</kbd> , <kbd>jobb</kbd> , <kbd>bal</kbd> , <kbd>enter</kbd> gombokkal lehet használni. Látszik is ahogy a joystick mozog :)

```
from sense_hat import SenseHat
from time import sleep

sense = SenseHat()

red = (200, 0, 0)
black = (0, 0, 0)
musicname0 = "11 - Bogozd ki (Csészényi tér 2006)"
musicname1 = "13 - Egy perccel tovább (Csészényi tér 2006)"
musicname2 = "14 - Ül és vár (Egy perccel tovább 2004)"
musicname3 = "15 - Sötét van (Egy perccel tovább 2004)"
musicname4 = "16 - Próbaterem Session 2015 (Kipakolta, Átszalad)"

#Fügvények
def play_pause():
  print("Playing:")
  displayH(musicname0)
  
def nextt():
  print("Playing:")
  displayH(musicname1)

def previous():
  print("Playing:")
  displayH(musicname2)

def volup():
  print("Vol UP")

def voldown():
  print("Vol DOWN")

def displayH(string):
  sense.show_message(string, text_colour=red, back_colour=black, scroll_speed=0.05)

while True:
  for event in sense.stick.get_events():
    if event.action == "pressed":
      if event.direction == "up":
          volup()
      elif event.direction == "down":
          voldown()
      elif event.direction == "left": 
          previous() # Bal
      elif event.direction == "right":
          nextt() # Jobb
      elif event.direction == "middle":
          play_pause()
      sleep(0.5)
      sense.clear()
            # gyro szezorok segítségével(rPI eszköz megrázásával) a shuffle füfvény hívása
```

**Comment by Sholwa** [comment]
@MasterPepinho 
hali tananyagban találtam egy lehetséges alternatívát logók rajzolásához. Tök jó :)
```
from sense_hat import SenseHat
sense = SenseHat()

g = (0, 255, 0) # Green
b = (0, 0, 0) # Black

pixels = [
    g, g, g, g, g, g, g, g,
    g, g, g, g, g, g, g, g,
    g, b, b, g, g, b, b, g,
    g, b, b, g, g, b, b, g,
    g, g, g, b, b, g, g, g,
    g, g, b, b, b, b, g, g,
    g, g, b, b, b, b, g, g,
    g, g, b, g, g, b, g, g
]

sense.set_pixels(pixels)
```

**Comment by MasterPepinho** [comment]
tényleg jó és egyszerűbb is, mint a sorokat és oszlopokat számolni

**Comment by Sholwa** [comment]
@MasterPepinho  Szia, kicsit utána olvastam ennek a szám scrollozás megszakításának. Bajos sajnos, nem lehet megszakítani a loop-on belül ahogy sejtettük. Külön szálon kell majd meghívnunk. Ezt viszont még nem tudom hogyan kell megtenni pythonban. itt lehet róla olvasni:[https://docs.python.org/3/library/threading.html](url)

Nem ástam jobban bele magam..... de meg kellene oldanunk ha akarunk számkijelzést.

**Comment by MasterPepinho** [comment]
Lehet, hogy hülyeség, de mi lenne, ha úgy csinálnánk, hogy lenne egy változó, léptetésnél betölteni a szám címét ebbe a változóba és azt iratnánk ki. Vajon akkor is végig kiírja előbb a szám címét és csak utána töltené be?

**Comment by Sholwa** [comment]
> Lehet, hogy hülyeség, de mi lenne, ha úgy csinálnánk, hogy lenne egy változó, léptetésnél betölteni a szám címét ebbe a változóba és azt iratnánk ki. Vajon akkor is végig kiírja előbb a szám címét és csak utána töltené be?

Szia, nem menne, mert a gond a show_message fügvénnyel van. Mindegy milyen változóból kapja azértéket, ha elindul akkor nem lehet megszakítani, mert az adott szálban fut amiből meghívod. Ezért kell külö szálon futtatni. Értsd mintha külön folyamatként futna. Szivacs de ez van.

**Comment by Sholwa** [comment]
@MasterPepinho a shuffle logót, illetve a matrix verziókat még megcsinálod?

**Comment by MasterPepinho** [comment]
@Sholwa igen, a mátrix verziónál az egyszerűsített play pause-ra gondolsz, ugye?

**Comment by Sholwa** [comment]
> @Sholwa igen, a mátrix verziónál az egyszerűsített play pause-ra gondolsz, ugye?

Igen

**Comment by MasterPepinho** [comment]
play: 
from sense_hat import SenseHat
sense = SenseHat()

g = (0, 255, 0) # Green
b = (0, 0, 0) # Black

pixels = [
       b, b, b, b, b, b, b, b,
    b, b, g, b, b, b, b, b,
    b, b, g, g, b, b, b, b,
    b, b, g, g, g, b, b, b,
    b, b, g, g, b, b, b, b,
    b, b, g, b, b, b, b, b,
    b, b, b, b, b, b, b, b,
    b, b, b, b, b, b, b, b
]
sense.set_pixels(pixels)

**Comment by MasterPepinho** [comment]
pause:
pixels = [
       b, b, b, b, b, b, b, b,
    b, g, g, b, g, g, b, b,
    b, g, g, b, g, g, b, b,
    b, g, g, b, g, g, b, b,
    b, g, g, b, g, g, b, b,
    b, g, g, b, g, g, b, b,
    b, b, b, b, b, b, b, b,
    b, b, b, b, b, b, b, b

]

**Comment by MasterPepinho** [comment]
vissza: 
pixels = [
    b, b, b, b, b, b, b, b,
    b, b, g, b, b, b, b, b,
    b, g, g, b, b, b, g, b,
    g, g, g, b, b, g, g, b,
    b, g, g, b, g, g, g, b,
    b, b, g, b, b, g, g, b,
    b, b, b, b, b, b, g, b,
    b, b, b, b, b, b, b, b


]

**Comment by MasterPepinho** [comment]
előre: 
pixels = [
    b, b, b, b, b, b, b, b,
    b, b, b, b, b, g, b, b,
    b, g, b, b, b, g, g, b,
    b, g, g, b, b, g, g, g,
    b, g, g, g, b, g, g, b,
    b, g, g, b, b, g, b, b,
    b, g, b, b, b, b, b, b,
    b, b, b, b, b, b, b, b

]

**Comment by MasterPepinho** [comment]
shuffle-re jobbat nem tudtam kialakítani:
pixels = [
    b, b, b, b, b, b, g, b,
    b, b, b, b, g, g, g, g,
    g, g, b, g, b, b, g, b,
    b, b, g, b, b, b, b, b,
    b, b, g, b, b, b, b, b,
    g, g, b, g, b, b, g, b,
    b, b, b, b, g, g, g, g,
    b, b, b, b, b, b, g, b

]

**Comment by Sholwa** [comment]
> shuffle-re jobbat nem tudtam kialakítani
> ]

kipróbáltam tök jó lett :)

**Comment by MasterPepinho** [comment]
szuper :)

**Comment by Sholwa** [comment]
A matrix verziójú logók beillesztve a programba. Számkijelzés nem lett megvalósítva. Ezen kívül Üdvözlő üzenet illetve hangerő állítás jelzése lett még megoldva, ami teszteléskor merült fel hogy hiányzik.
